// <auto-generated />
using System;
using Acme.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acme.Repositories.Migrations
{
    [DbContext(typeof(AcmeContext))]
    [Migration("20220710012501_NewTables")]
    partial class NewTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Acme.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Canada"
                        });
                });

            modelBuilder.Entity("Acme.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("Acme.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Abreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("State", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abreviation = "AL",
                            CountryId = 1,
                            Name = "Alabama"
                        },
                        new
                        {
                            Id = 2,
                            Abreviation = "AK",
                            CountryId = 1,
                            Name = "Alaska"
                        },
                        new
                        {
                            Id = 3,
                            Abreviation = "AZ",
                            CountryId = 1,
                            Name = "Arizona"
                        },
                        new
                        {
                            Id = 4,
                            Abreviation = "AR",
                            CountryId = 1,
                            Name = "Arkansas"
                        },
                        new
                        {
                            Id = 5,
                            Abreviation = "CA",
                            CountryId = 1,
                            Name = "California"
                        },
                        new
                        {
                            Id = 6,
                            Abreviation = "CO",
                            CountryId = 1,
                            Name = "Colorado"
                        },
                        new
                        {
                            Id = 7,
                            Abreviation = "CT",
                            CountryId = 1,
                            Name = "Connecticut"
                        },
                        new
                        {
                            Id = 8,
                            Abreviation = "DE",
                            CountryId = 1,
                            Name = "Delaware"
                        },
                        new
                        {
                            Id = 9,
                            Abreviation = "DC",
                            CountryId = 1,
                            Name = "District of Columbia"
                        },
                        new
                        {
                            Id = 10,
                            Abreviation = "FL",
                            CountryId = 1,
                            Name = "Florida"
                        },
                        new
                        {
                            Id = 11,
                            Abreviation = "GA",
                            CountryId = 1,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 12,
                            Abreviation = "HI",
                            CountryId = 1,
                            Name = "Hawaii"
                        },
                        new
                        {
                            Id = 13,
                            Abreviation = "ID",
                            CountryId = 1,
                            Name = "Idaho"
                        },
                        new
                        {
                            Id = 14,
                            Abreviation = "IL",
                            CountryId = 1,
                            Name = "Illinois"
                        },
                        new
                        {
                            Id = 15,
                            Abreviation = "IN",
                            CountryId = 1,
                            Name = "Indiana"
                        },
                        new
                        {
                            Id = 16,
                            Abreviation = "IA",
                            CountryId = 1,
                            Name = "Iowa"
                        },
                        new
                        {
                            Id = 17,
                            Abreviation = "KS",
                            CountryId = 1,
                            Name = "Kansas"
                        },
                        new
                        {
                            Id = 18,
                            Abreviation = "KY",
                            CountryId = 1,
                            Name = "Kentucky"
                        },
                        new
                        {
                            Id = 19,
                            Abreviation = "LA",
                            CountryId = 1,
                            Name = "Louisiana"
                        },
                        new
                        {
                            Id = 20,
                            Abreviation = "ME",
                            CountryId = 1,
                            Name = "Maine"
                        },
                        new
                        {
                            Id = 21,
                            Abreviation = "MD",
                            CountryId = 1,
                            Name = "Maryland"
                        },
                        new
                        {
                            Id = 22,
                            Abreviation = "MA",
                            CountryId = 1,
                            Name = "Massachusetts"
                        },
                        new
                        {
                            Id = 23,
                            Abreviation = "MI",
                            CountryId = 1,
                            Name = "Michigan"
                        },
                        new
                        {
                            Id = 24,
                            Abreviation = "MN",
                            CountryId = 1,
                            Name = "Minnesota"
                        },
                        new
                        {
                            Id = 25,
                            Abreviation = "MS",
                            CountryId = 1,
                            Name = "Mississippi"
                        },
                        new
                        {
                            Id = 26,
                            Abreviation = "MO",
                            CountryId = 1,
                            Name = "Missouri"
                        },
                        new
                        {
                            Id = 27,
                            Abreviation = "MT",
                            CountryId = 1,
                            Name = "Montana"
                        },
                        new
                        {
                            Id = 28,
                            Abreviation = "NE",
                            CountryId = 1,
                            Name = "Nebraska"
                        },
                        new
                        {
                            Id = 29,
                            Abreviation = "NV",
                            CountryId = 1,
                            Name = "Nevada"
                        },
                        new
                        {
                            Id = 30,
                            Abreviation = "NH",
                            CountryId = 1,
                            Name = "New Hampshire"
                        },
                        new
                        {
                            Id = 31,
                            Abreviation = "NJ",
                            CountryId = 1,
                            Name = "New Jersey"
                        },
                        new
                        {
                            Id = 32,
                            Abreviation = "NM",
                            CountryId = 1,
                            Name = "New Mexico"
                        },
                        new
                        {
                            Id = 33,
                            Abreviation = "NY",
                            CountryId = 1,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 34,
                            Abreviation = "NC",
                            CountryId = 1,
                            Name = "North Carolina"
                        },
                        new
                        {
                            Id = 35,
                            Abreviation = "ND",
                            CountryId = 1,
                            Name = "North Dakota"
                        },
                        new
                        {
                            Id = 36,
                            Abreviation = "OH",
                            CountryId = 1,
                            Name = "Ohio"
                        },
                        new
                        {
                            Id = 37,
                            Abreviation = "OK",
                            CountryId = 1,
                            Name = "Oklahoma"
                        },
                        new
                        {
                            Id = 38,
                            Abreviation = "OR",
                            CountryId = 1,
                            Name = "Oregon"
                        },
                        new
                        {
                            Id = 39,
                            Abreviation = "PA",
                            CountryId = 1,
                            Name = "Pennsylvania"
                        },
                        new
                        {
                            Id = 40,
                            Abreviation = "PR",
                            CountryId = 1,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 41,
                            Abreviation = "RI",
                            CountryId = 1,
                            Name = "Rhode Island"
                        },
                        new
                        {
                            Id = 42,
                            Abreviation = "SC",
                            CountryId = 1,
                            Name = "South Carolina"
                        },
                        new
                        {
                            Id = 43,
                            Abreviation = "SD",
                            CountryId = 1,
                            Name = "South Dakota"
                        },
                        new
                        {
                            Id = 44,
                            Abreviation = "TN",
                            CountryId = 1,
                            Name = "Tennessee"
                        },
                        new
                        {
                            Id = 45,
                            Abreviation = "TX",
                            CountryId = 1,
                            Name = "Texas"
                        },
                        new
                        {
                            Id = 46,
                            Abreviation = "UT",
                            CountryId = 1,
                            Name = "Utah"
                        },
                        new
                        {
                            Id = 47,
                            Abreviation = "VT",
                            CountryId = 1,
                            Name = "Vermont"
                        },
                        new
                        {
                            Id = 48,
                            Abreviation = "VA",
                            CountryId = 1,
                            Name = "Virginia"
                        },
                        new
                        {
                            Id = 49,
                            Abreviation = "WA",
                            CountryId = 1,
                            Name = "Washington"
                        },
                        new
                        {
                            Id = 50,
                            Abreviation = "WV",
                            CountryId = 1,
                            Name = "West Virginia"
                        },
                        new
                        {
                            Id = 51,
                            Abreviation = "WI",
                            CountryId = 1,
                            Name = "Wisconsin"
                        },
                        new
                        {
                            Id = 52,
                            Abreviation = "WY",
                            CountryId = 1,
                            Name = "Wyoming"
                        },
                        new
                        {
                            Id = 53,
                            Abreviation = "AB",
                            CountryId = 2,
                            Name = "Alberta"
                        },
                        new
                        {
                            Id = 54,
                            Abreviation = "BC",
                            CountryId = 2,
                            Name = "British Columbia"
                        },
                        new
                        {
                            Id = 55,
                            Abreviation = "MB",
                            CountryId = 2,
                            Name = "Manitoba"
                        },
                        new
                        {
                            Id = 56,
                            Abreviation = "NB",
                            CountryId = 2,
                            Name = "New Brunswick"
                        },
                        new
                        {
                            Id = 57,
                            Abreviation = "NL",
                            CountryId = 2,
                            Name = "Newfoundland and Labrador"
                        },
                        new
                        {
                            Id = 58,
                            Abreviation = "NS",
                            CountryId = 2,
                            Name = "Nova Scotia"
                        },
                        new
                        {
                            Id = 59,
                            Abreviation = "ON",
                            CountryId = 2,
                            Name = "Ontario"
                        },
                        new
                        {
                            Id = 60,
                            Abreviation = "PE",
                            CountryId = 2,
                            Name = "Prince Edward Island"
                        },
                        new
                        {
                            Id = 61,
                            Abreviation = "QC",
                            CountryId = 2,
                            Name = "Quebec"
                        },
                        new
                        {
                            Id = 62,
                            Abreviation = "SK",
                            CountryId = 2,
                            Name = "Saskatchewan"
                        });
                });

            modelBuilder.Entity("Acme.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoItem", (string)null);
                });

            modelBuilder.Entity("Acme.Models.Person", b =>
                {
                    b.HasOne("Acme.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Acme.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Acme.Models.State", b =>
                {
                    b.HasOne("Acme.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Acme.Models.Country", b =>
                {
                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
